name: build.yml
on:
  push:
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Pull and build
        shell: bash
        run: ./build-docker-image.sh
      - name: Read tag from file
        id: read_tag
        run: echo "tag=$(cat latest-tag.txt)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_tag.outputs.tag }}
          release_name: ${{ steps.read_tag.outputs.tag }}
          draft: false
          prerelease: false
