name: build.yml
on:
  push:
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Pull and build
        shell: bash
        id: build
        run: ./build-docker-image.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.build.outputs.tag }}
          files: |
            ${{ steps.build.outputs.bp }}/minio
